import type {
  Alert,
  CareProfessional,
  Connection,
  FamilyMember,
  GameSession,
  Guardian,
  Member,
  Memory,
  MemoryAlbum,
  ProfessionalNote,
  ProgressPoint,
  Reminder,
} from "./types";

export const members: Member[] = [
  {
    id: "m1",
    name: "Asha",
    age: 74,
    region: "Assam",
    language: "as",
    connectionCode: "SL-4827-AX",
    status: "active",
    interests: ["Family", "Bihu songs", "Gardening", "Tea garden walks"],
    hometown: "Guwahati",
    occupation: "Retired school teacher",
  },
  {
    id: "m2",
    name: "Riya",
    age: 69,
    region: "West Bengal",
    language: "bn",
    connectionCode: "SL-3391-KM",
    status: "active",
    interests: ["Rabindra sangeet", "Cooking", "Grandchildren"],
    hometown: "Siliguri",
    occupation: "Retired postal clerk",
  },
  {
    id: "m3",
    name: "Mohan",
    age: 81,
    region: "Manipur",
    language: "mni",
    connectionCode: "SL-7710-BQ",
    status: "attention",
    interests: ["Fishing", "Folk theatre", "Loktak lake"],
    hometown: "Imphal",
    occupation: "Retired farmer",
  },
];

export const guardians: Guardian[] = [
  {
    id: "g1",
    name: "Anita",
    relation: "Daughter",
    memberIds: ["m1"],
    language: "en",
    permissions: ["activity", "progress", "reminders", "memories", "alerts"],
  },
  {
    id: "g2",
    name: "Rahul",
    relation: "Son",
    memberIds: ["m2", "m3"],
    language: "hi",
    permissions: ["activity", "progress", "alerts"],
  },
];

export const professionals: CareProfessional[] = [
  {
    id: "p1",
    name: "Dr. Sharma",
    kind: "Doctor",
    memberIds: ["m1", "m2", "m3"],
    permissions: ["history", "trends", "adherence", "alerts", "notes"],
  },
  {
    id: "p2",
    name: "Bina Devi",
    kind: "ASHA Worker",
    memberIds: ["m1", "m3"],
    permissions: ["history", "adherence", "alerts"],
  },
  {
    id: "p3",
    name: "Nurse Lalrin",
    kind: "Nurse",
    memberIds: ["m2"],
    permissions: ["history", "adherence"],
  },
];

export const connections: Connection[] = [
  {
    id: "c1",
    memberId: "m1",
    personName: "Anita",
    personRole: "guardian",
    relation: "Daughter",
    status: "connected",
    permissions: ["View daily activity", "View progress", "Manage reminders", "Upload memories"],
  },
  {
    id: "c2",
    memberId: "m1",
    personName: "Rahul",
    personRole: "guardian",
    relation: "Son",
    status: "connected",
    permissions: ["View daily activity", "View progress", "Receive alerts"],
  },
  {
    id: "c3",
    memberId: "m1",
    personName: "Dr. Sharma",
    personRole: "professional",
    relation: "Doctor",
    status: "pending",
    permissions: ["Activity history", "Cognitive activity trends", "Reminder adherence", "Alerts"],
    durationDays: 30,
  },
  {
    id: "c4",
    memberId: "m1",
    personName: "Bina Devi",
    personRole: "professional",
    relation: "ASHA Worker",
    status: "connected",
    permissions: ["Activity history", "Reminder adherence"],
    durationDays: 90,
  },
];

export const familyMembers: FamilyMember[] = [
  { id: "f1", memberId: "m1", name: "Anita", relation: "Daughter", emoji: "👩" },
  { id: "f2", memberId: "m1", name: "Rahul", relation: "Son", emoji: "👨" },
  { id: "f3", memberId: "m1", name: "Bhupen", relation: "Husband", emoji: "👴" },
  { id: "f4", memberId: "m1", name: "Tora", relation: "Granddaughter", emoji: "👧" },
  { id: "f5", memberId: "m1", name: "Nayan", relation: "Grandson", emoji: "👦" },
];

export const albums: MemoryAlbum[] = [
  { id: "a1", memberId: "m1", title: "Family Moments", count: 10, offline: true, emoji: "👨‍👩‍👧" },
  { id: "a2", memberId: "m1", title: "Festival Memories", count: 9, offline: true, emoji: "🎉" },
  { id: "a3", memberId: "m1", title: "Memories From Home", count: 8, offline: false, emoji: "🏡" },
  { id: "a4", memberId: "m1", title: "People Who Matter", count: 12, offline: false, emoji: "💛" },
];

export const memories: Memory[] = [
  {
    id: "me1",
    memberId: "m1",
    albumId: "a1",
    title: "A Special Day",
    people: "Anita, Tora",
    place: "Guwahati",
    year: 2019,
    occasion: "Family gathering",
    story: "Asha’s daughter visited during the festival and everyone cooked together.",
    theme: "family",
    emoji: "🎊",
    offline: true,
  },
  {
    id: "me2",
    memberId: "m1",
    albumId: "a2",
    title: "Bihu Morning",
    people: "The whole family",
    place: "Village courtyard",
    year: 2016,
    occasion: "Bihu",
    story: "Dhol and pepa played from early morning and the children danced in new clothes.",
    theme: "festival",
    emoji: "🪘",
    offline: true,
  },
  {
    id: "me3",
    memberId: "m1",
    albumId: "a3",
    title: "The Old House",
    people: "Bhupen",
    place: "Jorhat",
    year: 1998,
    occasion: "Everyday life",
    story: "The tin roof, the guava tree and evening tea on the veranda.",
    theme: "home",
    emoji: "🏡",
    offline: false,
  },
  {
    id: "me4",
    memberId: "m1",
    albumId: "a1",
    title: "Tora’s First Day at School",
    people: "Tora",
    place: "Guwahati",
    year: 2014,
    occasion: "School day",
    story: "She held her grandmother’s hand all the way to the gate.",
    theme: "people",
    emoji: "🎒",
    offline: true,
  },
  {
    id: "me5",
    memberId: "m1",
    albumId: "a3",
    title: "Songs by the River",
    people: "Neighbours",
    place: "Brahmaputra bank",
    year: 2005,
    occasion: "Evening singing",
    story: "Everyone sang together as the boats went home.",
    theme: "music",
    emoji: "🎵",
    offline: false,
  },
  {
    id: "me6",
    memberId: "m1",
    albumId: "a4",
    title: "Tea Garden Walk",
    people: "Asha and Bhupen",
    place: "Sonitpur",
    year: 1994,
    occasion: "A quiet morning",
    story: "Mist over the tea bushes, and a flask of red tea.",
    theme: "nature",
    emoji: "🌿",
    offline: false,
  },
];

export const defaultReminders: Reminder[] = [
  {
    id: "r1",
    memberId: "m1",
    kind: "medicine",
    time: "08:00",
    labelKey: "reminders.medicine",
    priority: "high",
    done: true,
    emoji: "💊",
  },
  {
    id: "r2",
    memberId: "m1",
    kind: "hydration",
    time: "10:00",
    labelKey: "reminders.hydration",
    priority: "medium",
    done: false,
    emoji: "💧",
  },
  {
    id: "r3",
    memberId: "m1",
    kind: "activity",
    time: "11:00",
    labelKey: "reminders.activity",
    priority: "low",
    done: false,
    emoji: "🧠",
  },
  {
    id: "r4",
    memberId: "m1",
    kind: "meal",
    time: "13:00",
    labelKey: "reminders.meal",
    priority: "medium",
    done: true,
    emoji: "🍲",
  },
  {
    id: "r5",
    memberId: "m1",
    kind: "exercise",
    time: "17:00",
    labelKey: "reminders.exercise",
    priority: "medium",
    done: false,
    emoji: "🚶",
  },
  {
    id: "r6",
    memberId: "m1",
    kind: "medicine",
    time: "20:00",
    labelKey: "reminders.medicine",
    priority: "high",
    done: false,
    emoji: "💊",
  },
  {
    id: "r7",
    memberId: "m1",
    kind: "appointment",
    time: "Fri 11:30",
    labelKey: "reminders.appointment",
    priority: "high",
    done: false,
    emoji: "📅",
  },
];

export const gameSessions: GameSession[] = [
  { id: "s1", memberId: "m1", gameId: "pattern", level: 4, accuracy: 88, responseMs: 2100, attempts: 9, completed: true, date: "2026-09-01" },
  { id: "s2", memberId: "m1", gameId: "match", level: 3, accuracy: 76, responseMs: 3400, attempts: 12, completed: true, date: "2026-09-02" },
  { id: "s3", memberId: "m1", gameId: "find", level: 2, accuracy: 70, responseMs: 2800, attempts: 6, completed: true, date: "2026-09-03" },
  { id: "s4", memberId: "m1", gameId: "signals", level: 3, accuracy: 82, responseMs: 2500, attempts: 8, completed: true, date: "2026-09-04" },
  { id: "s5", memberId: "m2", gameId: "match", level: 4, accuracy: 91, responseMs: 2200, attempts: 14, completed: true, date: "2026-09-04" },
  { id: "s6", memberId: "m3", gameId: "pattern", level: 2, accuracy: 58, responseMs: 4100, attempts: 7, completed: false, date: "2026-09-05" },
];

export const alerts: Alert[] = [
  {
    id: "al1",
    memberId: "m1",
    emoji: "💊",
    titleKey: "Evening medicine still pending",
    detail: "Asha has not marked the evening medicine yet.",
    when: "Today, 8:20 pm",
    tone: "attention",
  },
  {
    id: "al2",
    memberId: "m1",
    emoji: "🧠",
    titleKey: "Activity pattern changed",
    detail: "Slightly fewer memory activities this week than last week.",
    when: "Today, 9:00 am",
    tone: "info",
  },
  {
    id: "al3",
    memberId: "m1",
    emoji: "👩‍⚕️",
    titleKey: "New professional note",
    detail: "Bina Devi added an observation after her home visit.",
    when: "Yesterday",
    tone: "info",
  },
  {
    id: "al4",
    memberId: "m3",
    emoji: "🚶",
    titleKey: "Evening walk not completed",
    detail: "Mohan has missed the evening walk three days in a row.",
    when: "Yesterday",
    tone: "attention",
  },
];

export const notes: ProfessionalNote[] = [
  {
    id: "n1",
    memberId: "m1",
    author: "Bina Devi",
    date: "2026-09-05",
    activity: "Family photo activity",
    note: "Member showed strong engagement during the family photo activity.",
    followUp: "Continue family-themed memories three times a week.",
  },
  {
    id: "n2",
    memberId: "m2",
    author: "Dr. Sharma",
    date: "2026-09-03",
    activity: "Memory Match",
    note: "Comfortable at 4 pairs, response time steady.",
    followUp: "Hold difficulty for another week.",
  },
  {
    id: "n3",
    memberId: "m3",
    author: "Dr. Sharma",
    date: "2026-09-02",
    activity: "Daily routine",
    note: "Routine recall varies in the evening. Family informed gently.",
    followUp: "Add a voice reminder at 5 pm.",
  },
];

export const weekProgress: ProgressPoint[] = [
  { day: "Mon", games: 2, memories: 3, adherence: 90, hydration: 4 },
  { day: "Tue", games: 3, memories: 2, adherence: 85, hydration: 5 },
  { day: "Wed", games: 1, memories: 4, adherence: 100, hydration: 3 },
  { day: "Thu", games: 3, memories: 3, adherence: 75, hydration: 4 },
  { day: "Fri", games: 2, memories: 5, adherence: 95, hydration: 5 },
  { day: "Sat", games: 4, memories: 4, adherence: 80, hydration: 4 },
  { day: "Sun", games: 2, memories: 2, adherence: 90, hydration: 3 },
];

export const rootsCards = [
  { key: "region", emoji: "🌄", title: "My Region", detail: "Assam — river plains, tea gardens and rain." },
  { key: "language", emoji: "🗣️", title: "My Language", detail: "Assamese, with Hindi at the market." },
  { key: "music", emoji: "🎵", title: "My Music", detail: "Bihu songs, borgeet, evening radio." },
  { key: "cinema", emoji: "🎬", title: "My Cinema", detail: "Old Assamese films watched with family." },
  { key: "stories", emoji: "📖", title: "My Stories", detail: "Grandmother’s folk tales at bedtime." },
  { key: "culture", emoji: "🎭", title: "My Culture", detail: "Bihu dance, gamosa, community feasts." },
  { key: "places", emoji: "📍", title: "My Places", detail: "Guwahati, Jorhat, the Brahmaputra bank." },
  { key: "people", emoji: "👨‍👩‍👧", title: "My People", detail: "Bhupen, Anita, Rahul, Tora, Nayan." },
];
