import type {
  Alert,
  CareProfessional,
  Connection,
  FamilyMember,
  GameSession,
  Guardian,
  Member,
  Memory,
  MemoryAlbum,
  ProfessionalNote,
  ProgressPoint,
  Reminder,
  RootsCard,
} from "./types";

export const members: Member[] = [
  {
    id: "m1",
    name: "Asha",
    age: 74,
    region: "Assam",
    language: "as",
    connectionCode: "SL-4827-AX",
    status: "active",
    interests: ["Family", "Bihu songs", "Gardening", "Tea garden walks"],
    hometown: "Guwahati",
    occupation: "Retired school teacher",
  },
  {
    id: "m2",
    name: "Riya",
    age: 69,
    region: "West Bengal",
    language: "bn",
    connectionCode: "SL-3391-KM",
    status: "active",
    interests: ["Rabindra sangeet", "Cooking", "Grandchildren", "Durga Puja"],
    hometown: "Siliguri",
    occupation: "Retired postal clerk",
  },
  {
    id: "m3",
    name: "Mohan",
    age: 81,
    region: "Manipur",
    language: "mni",
    connectionCode: "SL-7710-BQ",
    status: "attention",
    interests: ["Fishing", "Folk theatre", "Loktak lake", "Lai Haraoba"],
    hometown: "Imphal",
    occupation: "Retired farmer",
  },
];

export const guardians: Guardian[] = [
  {
    id: "g1",
    name: "Anita",
    relation: "Daughter",
    memberIds: ["m1"],
    language: "en",
    permissions: ["view_activity", "view_progress", "manage_reminders", "upload_memories", "receive_alerts"],
  },
  {
    id: "g2",
    name: "Rahul",
    relation: "Son",
    memberIds: ["m2", "m3"],
    language: "hi",
    permissions: ["view_activity", "view_progress", "receive_alerts"],
  },
];

export const professionals: CareProfessional[] = [
  {
    id: "p1",
    name: "Dr. Sharma",
    kind: "Doctor",
    memberIds: ["m1", "m2", "m3"],
    permissions: ["view_history", "view_trends", "view_adherence", "view_alerts", "add_observations"],
  },
  {
    id: "p2",
    name: "Bina Devi",
    kind: "ASHA Worker",
    memberIds: ["m1", "m3"],
    permissions: ["view_history", "view_adherence", "view_alerts"],
  },
  {
    id: "p3",
    name: "Nurse Lalrin",
    kind: "Nurse",
    memberIds: ["m2"],
    permissions: ["view_history", "view_adherence"],
  },
];

export const connections: Connection[] = [
  {
    id: "c1",
    memberId: "m1",
    personName: "Anita",
    personRole: "guardian",
    relation: "Daughter",
    status: "connected",
    permissions: ["View daily activity", "View progress", "Manage reminders", "Upload memories"],
  },
  {
    id: "c2",
    memberId: "m1",
    personName: "Rahul",
    personRole: "guardian",
    relation: "Son",
    status: "connected",
    permissions: ["View daily activity", "View progress", "Receive alerts"],
  },
  {
    id: "c3",
    memberId: "m1",
    personName: "Dr. Sharma",
    personRole: "professional",
    relation: "Doctor",
    status: "pending",
    permissions: ["Activity history", "Cognitive activity trends", "Reminder adherence", "Alerts"],
    durationDays: 30,
  },
  {
    id: "c4",
    memberId: "m1",
    personName: "Bina Devi",
    personRole: "professional",
    relation: "ASHA Worker",
    status: "connected",
    permissions: ["Activity history", "Reminder adherence"],
    durationDays: 90,
  },
  {
    id: "c5",
    memberId: "m2",
    personName: "Rahul",
    personRole: "guardian",
    relation: "Son",
    status: "connected",
    permissions: ["View daily activity", "View progress", "Receive alerts"],
  },
  {
    id: "c6",
    memberId: "m3",
    personName: "Rahul",
    personRole: "guardian",
    relation: "Son",
    status: "connected",
    permissions: ["View daily activity", "View progress", "Receive alerts"],
  },
];

export const familyMembers: FamilyMember[] = [
  { id: "f1", memberId: "m1", name: "Anita", relation: "Daughter", emoji: "👩" },
  { id: "f2", memberId: "m1", name: "Rahul", relation: "Son", emoji: "👨" },
  { id: "f3", memberId: "m1", name: "Bhupen", relation: "Husband", emoji: "👴" },
  { id: "f4", memberId: "m1", name: "Tora", relation: "Granddaughter", emoji: "👧" },
  { id: "f5", memberId: "m1", name: "Nayan", relation: "Grandson", emoji: "👦" },
  { id: "f6", memberId: "m2", name: "Rahul", relation: "Son", emoji: "👨" },
  { id: "f7", memberId: "m2", name: "Soma", relation: "Daughter-in-law", emoji: "👩" },
  { id: "f8", memberId: "m2", name: "Priya", relation: "Granddaughter", emoji: "👧" },
  { id: "f9", memberId: "m3", name: "Tomba", relation: "Son", emoji: "👨" },
  { id: "f10", memberId: "m3", name: "Memma", relation: "Wife", emoji: "👵" },
];

export const albums: MemoryAlbum[] = [
  { id: "a1", memberId: "m1", title: "Family Moments", count: 10, offline: true, emoji: "👨‍👩‍👧" },
  { id: "a2", memberId: "m1", title: "Festival Memories", count: 9, offline: true, emoji: "🎉" },
  { id: "a3", memberId: "m1", title: "Memories From Home", count: 8, offline: false, emoji: "🏡" },
  { id: "a4", memberId: "m1", title: "People Who Matter", count: 12, offline: false, emoji: "💛" },
  { id: "a5", memberId: "m2", title: "Family Moments", count: 8, offline: true, emoji: "👨‍👩‍👧" },
  { id: "a6", memberId: "m2", title: "Durga Puja", count: 6, offline: true, emoji: "🎊" },
  { id: "a7", memberId: "m2", title: "Kitchen Stories", count: 5, offline: false, emoji: "🍲" },
  { id: "a8", memberId: "m3", title: "Loktak Memories", count: 7, offline: true, emoji: "🌊" },
  { id: "a9", memberId: "m3", title: "Festival Days", count: 6, offline: false, emoji: "🎭" },
];

export const memories: Memory[] = [
  // Asha (m1) memories
  {
    id: "me1",
    memberId: "m1",
    albumId: "a1",
    title: "A Special Day",
    people: "Anita, Tora",
    place: "Guwahati",
    year: 2019,
    occasion: "Family gathering",
    story: "Asha's daughter visited during the festival and everyone cooked together.",
    theme: "family",
    emoji: "🎊",
    offline: true,
  },
  {
    id: "me2",
    memberId: "m1",
    albumId: "a2",
    title: "Bihu Morning",
    people: "The whole family",
    place: "Village courtyard",
    year: 2016,
    occasion: "Bihu",
    story: "Dhol and pepa played from early morning and the children danced in new clothes.",
    theme: "festival",
    emoji: "🪘",
    offline: true,
  },
  {
    id: "me3",
    memberId: "m1",
    albumId: "a3",
    title: "The Old House",
    people: "Bhupen",
    place: "Jorhat",
    year: 1998,
    occasion: "Everyday life",
    story: "The tin roof, the guava tree and evening tea on the veranda.",
    theme: "home",
    emoji: "🏡",
    offline: false,
  },
  {
    id: "me4",
    memberId: "m1",
    albumId: "a1",
    title: "Tora's First Day at School",
    people: "Tora",
    place: "Guwahati",
    year: 2014,
    occasion: "School day",
    story: "She held her grandmother's hand all the way to the gate.",
    theme: "people",
    emoji: "🎒",
    offline: true,
  },
  {
    id: "me5",
    memberId: "m1",
    albumId: "a3",
    title: "Songs by the River",
    people: "Neighbours",
    place: "Brahmaputra bank",
    year: 2005,
    occasion: "Evening singing",
    story: "Everyone sang together as the boats went home.",
    theme: "music",
    emoji: "🎵",
    offline: false,
  },
  {
    id: "me6",
    memberId: "m1",
    albumId: "a4",
    title: "Tea Garden Walk",
    people: "Asha and Bhupen",
    place: "Sonitpur",
    year: 1994,
    occasion: "A quiet morning",
    story: "Mist over the tea bushes, and a flask of red tea.",
    theme: "nature",
    emoji: "🌿",
    offline: false,
  },
  // Riya (m2) memories
  {
    id: "me7",
    memberId: "m2",
    albumId: "a5",
    title: "Durga Puja Celebrations",
    people: "Soma, Priya",
    place: "Siliguri",
    year: 2018,
    occasion: "Durga Puja",
    story: "The pandal was beautiful and Priya wore her first sari.",
    theme: "festival",
    emoji: "🎊",
    offline: true,
  },
  {
    id: "me8",
    memberId: "m2",
    albumId: "a5",
    title: "Cooking with Grandma",
    people: "Priya",
    place: "Kitchen at home",
    year: 2021,
    occasion: "Weekend",
    story: "Priya learned to make rosogolla for the first time. It took three tries.",
    theme: "family",
    emoji: "🍲",
    offline: true,
  },
  {
    id: "me9",
    memberId: "m2",
    albumId: "a7",
    title: "Retirement Party",
    people: "Post office colleagues",
    place: "Siliguri Post Office",
    year: 2015,
    occasion: "Retirement",
    story: "Thirty years of sorting letters. They gave Riya a beautiful shawl.",
    theme: "people",
    emoji: "📮",
    offline: false,
  },
  {
    id: "me10",
    memberId: "m2",
    albumId: "a6",
    title: "Morning Walks",
    people: "Neighbours",
    place: "Mahananda river bank",
    year: 2020,
    occasion: "Daily routine",
    story: "The cool breeze from the hills and the sound of birds.",
    theme: "nature",
    emoji: "🌅",
    offline: false,
  },
  {
    id: "me11",
    memberId: "m2",
    albumId: "a5",
    title: "Rabindra Jayanti",
    people: "Family and friends",
    place: "Community hall",
    year: 2017,
    occasion: "Cultural event",
    story: "Riya sang 'Purano Sei Diner Kotha' and everyone joined in.",
    theme: "music",
    emoji: "🎵",
    offline: true,
  },
  // Mohan (m3) memories
  {
    id: "me12",
    memberId: "m3",
    albumId: "a8",
    title: "Fishing at Loktak",
    people: "Tomba",
    place: "Loktak Lake",
    year: 2010,
    occasion: "Weekend outing",
    story: "They caught five fish and cooked them by the lakeside.",
    theme: "nature",
    emoji: "🐟",
    offline: true,
  },
  {
    id: "me13",
    memberId: "m3",
    albumId: "a9",
    title: "Lai Haraoba Festival",
    people: "The whole village",
    place: "Imphal",
    year: 2012,
    occasion: "Lai Haraoba",
    story: "The maibis danced and the drums echoed through the valley.",
    theme: "festival",
    emoji: "🎭",
    offline: true,
  },
  {
    id: "me14",
    memberId: "m3",
    albumId: "a8",
    title: "The Rice Field",
    people: "Memma",
    place: "Imphal Valley",
    year: 1995,
    occasion: "Harvest season",
    story: "Golden paddies stretching to the hills. Everyone helped with the harvest.",
    theme: "home",
    emoji: "🌾",
    offline: false,
  },
  {
    id: "me15",
    memberId: "m3",
    albumId: "a9",
    title: "Tomba's Wedding",
    people: "Tomba, Memma, relatives",
    place: "Imphal",
    year: 2008,
    occasion: "Wedding",
    story: "Traditional Manipuri wedding with all the rituals. The happiest day.",
    theme: "family",
    emoji: "💒",
    offline: true,
  },
  {
    id: "me16",
    memberId: "m3",
    albumId: "a8",
    title: "Shumang Leela Evening",
    people: "Village friends",
    place: "Imphal",
    year: 2014,
    occasion: "Cultural event",
    story: "The courtyard theatre made everyone laugh and cry.",
    theme: "music",
    emoji: "🎭",
    offline: false,
  },
];

export const defaultReminders: Reminder[] = [
  {
    id: "r1",
    memberId: "m1",
    kind: "medicine",
    time: "08:00",
    labelKey: "reminders.medicine",
    priority: "high",
    done: true,
    emoji: "💊",
  },
  {
    id: "r2",
    memberId: "m1",
    kind: "hydration",
    time: "10:00",
    labelKey: "reminders.hydration",
    priority: "medium",
    done: false,
    emoji: "💧",
  },
  {
    id: "r3",
    memberId: "m1",
    kind: "activity",
    time: "11:00",
    labelKey: "reminders.activity",
    priority: "low",
    done: false,
    emoji: "🧠",
  },
  {
    id: "r4",
    memberId: "m1",
    kind: "meal",
    time: "13:00",
    labelKey: "reminders.meal",
    priority: "medium",
    done: true,
    emoji: "🍲",
  },
  {
    id: "r5",
    memberId: "m1",
    kind: "exercise",
    time: "17:00",
    labelKey: "reminders.exercise",
    priority: "medium",
    done: false,
    emoji: "🚶",
  },
  {
    id: "r6",
    memberId: "m1",
    kind: "medicine",
    time: "20:00",
    labelKey: "reminders.medicine",
    priority: "high",
    done: false,
    emoji: "💊",
  },
  {
    id: "r7",
    memberId: "m1",
    kind: "appointment",
    time: "Fri 11:30",
    labelKey: "reminders.appointment",
    priority: "high",
    done: false,
    emoji: "📅",
  },
];

export const gameSessions: GameSession[] = [
  { id: "s1", memberId: "m1", gameId: "pattern", level: 4, accuracy: 88, responseMs: 2100, attempts: 9, completed: true, date: "2026-09-01" },
  { id: "s2", memberId: "m1", gameId: "match", level: 3, accuracy: 76, responseMs: 3400, attempts: 12, completed: true, date: "2026-09-02" },
  { id: "s3", memberId: "m1", gameId: "find", level: 2, accuracy: 70, responseMs: 2800, attempts: 6, completed: true, date: "2026-09-03" },
  { id: "s4", memberId: "m1", gameId: "signals", level: 3, accuracy: 82, responseMs: 2500, attempts: 8, completed: true, date: "2026-09-04" },
  { id: "s5", memberId: "m2", gameId: "match", level: 4, accuracy: 91, responseMs: 2200, attempts: 14, completed: true, date: "2026-09-04" },
  { id: "s6", memberId: "m3", gameId: "pattern", level: 2, accuracy: 58, responseMs: 4100, attempts: 7, completed: false, date: "2026-09-05" },
  { id: "s7", memberId: "m2", gameId: "pattern", level: 3, accuracy: 85, responseMs: 2600, attempts: 10, completed: true, date: "2026-09-05" },
  { id: "s8", memberId: "m2", gameId: "find", level: 3, accuracy: 80, responseMs: 2900, attempts: 8, completed: true, date: "2026-09-06" },
  { id: "s9", memberId: "m3", gameId: "match", level: 2, accuracy: 62, responseMs: 3800, attempts: 9, completed: true, date: "2026-09-06" },
  { id: "s10", memberId: "m3", gameId: "signals", level: 2, accuracy: 55, responseMs: 4500, attempts: 6, completed: false, date: "2026-09-07" },
];

export const alerts: Alert[] = [
  {
    id: "al1",
    memberId: "m1",
    emoji: "💊",
    titleKey: "alerts.medicinePending",
    detail: "Asha has not marked the evening medicine yet.",
    when: "Today, 8:20 pm",
    tone: "attention",
  },
  {
    id: "al2",
    memberId: "m1",
    emoji: "🧠",
    titleKey: "alerts.activityChanged",
    detail: "Slightly fewer memory activities this week than last week.",
    when: "Today, 9:00 am",
    tone: "info",
  },
  {
    id: "al3",
    memberId: "m1",
    emoji: "👩‍⚕️",
    titleKey: "alerts.newNote",
    detail: "Bina Devi added an observation after her home visit.",
    when: "Yesterday",
    tone: "info",
  },
  {
    id: "al4",
    memberId: "m3",
    emoji: "🚶",
    titleKey: "alerts.walkMissed",
    detail: "Mohan has missed the evening walk three days in a row.",
    when: "Yesterday",
    tone: "attention",
  },
  {
    id: "al5",
    memberId: "m2",
    emoji: "💧",
    titleKey: "alerts.hydrationLow",
    detail: "Riya had only 2 glasses of water today.",
    when: "Today, 4:00 pm",
    tone: "info",
  },
];

export const notes: ProfessionalNote[] = [
  {
    id: "n1",
    memberId: "m1",
    author: "Bina Devi",
    date: "2026-09-05",
    activity: "Family photo activity",
    note: "Member showed strong engagement during the family photo activity.",
    followUp: "Continue family-themed memories three times a week.",
  },
  {
    id: "n2",
    memberId: "m2",
    author: "Dr. Sharma",
    date: "2026-09-03",
    activity: "Memory Match",
    note: "Comfortable at 4 pairs, response time steady.",
    followUp: "Hold difficulty for another week.",
  },
  {
    id: "n3",
    memberId: "m3",
    author: "Dr. Sharma",
    date: "2026-09-02",
    activity: "Daily routine",
    note: "Routine recall varies in the evening. Family informed gently.",
    followUp: "Add a voice reminder at 5 pm.",
  },
];

export const weekProgress: ProgressPoint[] = [
  { day: "Mon", games: 2, memories: 3, adherence: 90, hydration: 4 },
  { day: "Tue", games: 3, memories: 2, adherence: 85, hydration: 5 },
  { day: "Wed", games: 1, memories: 4, adherence: 100, hydration: 3 },
  { day: "Thu", games: 3, memories: 3, adherence: 75, hydration: 4 },
  { day: "Fri", games: 2, memories: 5, adherence: 95, hydration: 5 },
  { day: "Sat", games: 4, memories: 4, adherence: 80, hydration: 4 },
  { day: "Sun", games: 2, memories: 2, adherence: 90, hydration: 3 },
];

export const rootsCardsData: Record<string, RootsCard[]> = {
  m1: [
    { key: "region", emoji: "🌄", titleKey: "roots.region", detailKey: "roots.m1.region" },
    { key: "language", emoji: "🗣️", titleKey: "roots.language", detailKey: "roots.m1.language" },
    { key: "music", emoji: "🎵", titleKey: "roots.music", detailKey: "roots.m1.music" },
    { key: "cinema", emoji: "🎬", titleKey: "roots.cinema", detailKey: "roots.m1.cinema" },
    { key: "stories", emoji: "📖", titleKey: "roots.stories", detailKey: "roots.m1.stories" },
    { key: "culture", emoji: "🎭", titleKey: "roots.culture", detailKey: "roots.m1.culture" },
    { key: "places", emoji: "📍", titleKey: "roots.places", detailKey: "roots.m1.places" },
    { key: "people", emoji: "👨‍👩‍👧", titleKey: "roots.people", detailKey: "roots.m1.people" },
  ],
  m2: [
    { key: "region", emoji: "🌄", titleKey: "roots.region", detailKey: "roots.m2.region" },
    { key: "language", emoji: "🗣️", titleKey: "roots.language", detailKey: "roots.m2.language" },
    { key: "music", emoji: "🎵", titleKey: "roots.music", detailKey: "roots.m2.music" },
    { key: "cinema", emoji: "🎬", titleKey: "roots.cinema", detailKey: "roots.m2.cinema" },
    { key: "stories", emoji: "📖", titleKey: "roots.stories", detailKey: "roots.m2.stories" },
    { key: "culture", emoji: "🎭", titleKey: "roots.culture", detailKey: "roots.m2.culture" },
    { key: "places", emoji: "📍", titleKey: "roots.places", detailKey: "roots.m2.places" },
    { key: "people", emoji: "👨‍👩‍👧", titleKey: "roots.people", detailKey: "roots.m2.people" },
  ],
  m3: [
    { key: "region", emoji: "🌄", titleKey: "roots.region", detailKey: "roots.m3.region" },
    { key: "language", emoji: "🗣️", titleKey: "roots.language", detailKey: "roots.m3.language" },
    { key: "music", emoji: "🎵", titleKey: "roots.music", detailKey: "roots.m3.music" },
    { key: "cinema", emoji: "🎬", titleKey: "roots.cinema", detailKey: "roots.m3.cinema" },
    { key: "stories", emoji: "📖", titleKey: "roots.stories", detailKey: "roots.m3.stories" },
    { key: "culture", emoji: "🎭", titleKey: "roots.culture", detailKey: "roots.m3.culture" },
    { key: "places", emoji: "📍", titleKey: "roots.places", detailKey: "roots.m3.places" },
    { key: "people", emoji: "👨‍👩‍👧", titleKey: "roots.people", detailKey: "roots.m3.people" },
  ],
};
